name: Update voter team

on:
  push:
    branches:
      - main
    # Prevent infinite loops when this action pushes commits
    paths-ignore:
      - scripts/invited.txt

# This workflow changes state, we shouldn't run multiple at the same time!
concurrency:
  group: ${{ github.workflow }}
  # Canceling could leave us in a bad state
  cancel-in-progress: false

jobs:
  update-voter-team:
    runs-on: ubuntu-latest
    name: Update voter team
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>'

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}

      - uses: cachix/install-nix-action@v27

      - name: Update team
        run: ./scripts/update-voter-team.sh
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          ORG: ${{ github.repository_owner }}
          VOTER_TEAM: ${{ vars.VOTER_TEAM }}
